services:
  # A Node.js web service
  - type: web
    name: servionai-whatsapp
    env: node
    plan: standard
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSIONS_DIR
        value: /sessions
      - key: PORT
        fromService:
          name: servionai-whatsapp
          type: web
          property: port
    disk:
      name: sessions-data
      mountPath: /var/data
      sizeGB: 1 